# Generated by Django 2.1.1 on 2018-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='document',
            name='project_video',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
